name: ci

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          pip install poetry
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - run: |
          poetry build
      - run: |
          poetry publish
  wait-for-pypi-propigation:
    runs-on: ubuntu-latest
    needs: [pypi]
    steps:
      - run: sleep 60
  container:
    runs-on: ubuntu-latest
    needs: [wait-for-pypi-propigation]
    permissions:
      packages: write
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64, linux/arm64
          build-args: |
            APP_NAME=${{ github.event.repository.name }}
            APP_VERSION=${{ github.ref_name }}
          tags: |
            ghcr.io/${{github.repository}}:${{ github.ref_name }}
            ghcr.io/${{github.repository}}:latest
